sonar.organization=maps
sonar.projectName=maps-apps
sonar.projectVersion=1.0
sonar.projectKey=moneyandpensionsservice_maps-apps

sonar.sources=apps,libs

sonar.exclusions=**/node_modules/**/*, \
                 **/bin/**/*, \
                 **/obj/**/*, \
                 **/__snapshots__/**,**/*.snap, \
                 **/public/**/*.map, \
                 **/public/iframeResizer*.js, \
                 **/public/iframeResizer*.map, \
                 **/fixtures/**, \
                 **/__mocks__/**, \
                 **/mocks/**, \
                 **/*.stories.*, \
                 **/apps/e2e/salary-calculator-e2e/**, \
                 **/apps/moneyhelper-tools/**, \
                 **/apps/e2e/moneyhelper-tools/**, \
                 **/apps/e2e/moneyhelper-tools*/**, \
                 **/apps/moneyhelper-tools/data/**, \
                 **/apps/money-adviser-network/data/**, \
                 **/apps/debt-advice-locator/data/**, \
                 **/apps/budget-planner/data/**, \
                 **/apps/compare-accounts/data/**, \
                 **/apps/credit-rejection/data/**, \
                 **/apps/credit-options/data/**, \
                 **/apps/tools-index/data/**, \
                 **/apps/standard-financial-statement/data/**, \
                 **/apps/adjustable-income-calculator/data/**, \
                 **/apps/cash-in-chunks/data/**, \
                 **/apps/guaranteed-income-estimator/data/**, \
                 **/apps/learning-pathway/data/**, \
                 **/apps/leave-pot-untouched/data/**, \
                 **/apps/retirement-budget-planner/data/**, \
                 **/apps/retirement-guidance/data/**, \
                 **/apps/stamp-duty-calculator/data/**, \
                 **/apps/savings-calculator/data/**, \
                 **/apps/take-whole-pot/data/**, \
                 **/apps/midlife-mot/data/**, \
                 **/apps/salary-calculator/data/**, \
                 **/apps/travel-insurance-directory/data/**, \
                 **/apps/travel-insurance-directory/pages/api/mocks/**, \
                 **/apps/travel-insurance-directory/instrumentation.ts, \
                 **/apps/standard-financial-statement/redirects.js, \
                 **/apps/savings-calculator/utils/savingsCalculatorValidationInputs.ts, \
                 **/apps/evidence-hub/data/**, \
                 **/apps/fuel-finder/data/**, \
                 **/apps/pension-type-tool/data/**, \
                 **/apps/workplace-pension-calculator/data/**, \
                 **/apps/pension-calculator/data/**, \
                 **/apps/mortgage-affordability/data/**, \
                 **/scripts/**/*, \

sonar.tests.inclusions=./apps/baby-cost-calculator/**/*.test.*, \
                       ./apps/pensionwise-appointment/**/*.test.*, \
                       ./apps/pensionwise-triage/**/*.test.*, \
                       ./apps/pension-type-tool/**/*.test.*, \
                       ./apps/moneyhelper-tools/**/*.test.*, \
                       ./apps/money-adviser-network/**/*.test.*, \
                       ./apps/pensions-dashboard/**/*.test.*, \
                       ./apps/moneyhelper-contact-forms/**/*.test.*, \
                       ./apps/budget-planner/**/*.test.*, \
                       ./apps/standard-financial-statement/**/*.test.*, \
                       ./apps/evidence-hub/**/*.test.*, \
                       ./apps/debt-advice-locator/**/*.test.*, \
                       ./apps/compare-accounts/**/*.test.*, \
                       ./apps/guaranteed-income-estimator/**/*.test.*, \
                       ./apps/cash-in-chunks/**/*.test.*, \
                       ./apps/adjustable-income-calculator/**/*.test.*, \
                       ./apps/leave-pot-untouched/**/*.test.*, \
                       ./apps/learning-pathway/**/*.test.*, \
                       ./apps/take-whole-pot/**/*.test.*, \
                       ./apps/credit-rejection/**/*.test.*, \
                       ./apps/credit-options/**/*.test.*, \
                       ./apps/mortgage-calculator/**/*.test.*, \
                       ./apps/tools-index/**/*.test.*, \
                       ./apps/mortgage-affordability/**/*.test.*, \
                       ./apps/redundancy-pay-calculator/**/*.test.*, \
                       ./apps/retirement-budget-planner/**/*.test.*, \
                       ./apps/retirement-guidance/**/*.test.*, \
                       ./apps/savings-calculator/**/*.test.*, \
                       ./apps/stamp-duty-calculator/**/*.test.*, \
                       ./apps/baby-money-timeline/**/*.test.*, \
                       ./apps/midlife-mot/**/*.test.*, \
                       ./apps/salary-calculator/**/*.test.*, \
                       ./apps/travel-insurance-directory/**/*.test.*, \
                       ./apps/fuel-finder/**/*.test.*, \
                       ./apps/workplace-pension-calculator/**/*.test.*, \
                       ./apps/pension-calculator/**/*.test.*, \
                       ./apps/e2e/**/*.cy.ts, \
                       ./apps/e2e/**/*.spec.ts

sonar.coverage.exclusions=**/*.json, \
                          **/*.stories.*, \
                          **/*.test.*, \
                          **/*.config.*, \
                          **/assets/**, \
                          **/pages/**, \
                          **/public/**, \
                          **/styles/**, \
                          **/api/**, \
                          **/*index.ts*, \
                          **/*-e2e/**, \
                          **/libs/shared/utils/src/e2e/**, \
                          **/apps/baby-cost-calculator/data/**, \
                          **/apps/moneyhelper-tools/data/**, \
                          **/apps/money-adviser-network/data/**, \
                          **/apps/budget-planner/data/**, \
                          **/apps/compare-accounts/data/**, \
                          **/apps/credit-rejection/data/**, \
                          **/apps/credit-options/data/**, \
                          **/apps/mortgage-calculator/data/**, \
                          **/apps/guaranteed-income-estimator/data/**, \
                          **/apps/cash-in-chunks-calculator/data/**, \
                          **/apps/adjustable-income-calculator/data/**, \
                          **/apps/learning-pathway/data/**, \
                          **/apps/leave-pot-untouched/data/**, \
                          **/apps/standard-financial-statement/data/**, \
                          **/apps/evidence-hub/data/**, \
                          **/apps/mortgage-affordability/data/**, \
                          **/apps/stamp-duty-calculator/data/**, \
                          **/apps/savings-calculator/data/**, \
                          **/apps/credit-rejection/CONSTANTS.ts, \
                          **/apps/credit-options/CONSTANTS.ts, \
                          **/apps/redundancy-pay-calculator/data/**, \
                          **/apps/redundancy-pay-calculator/CONSTANTS.ts, \
                          **/apps/retirement-guidance/data/**, \
                          **/apps/baby-money-timeline/data/**, \
                          **/apps/baby-money-timeline/CONSTANTS.ts, \
                          **/apps/baby-money-timeline/utils/timelineCalendar.ts, \
                          **/apps/midlife-mot/data/**, \
                          **/apps/midlife-mot/CONSTANTS.ts, \
                          **/app/**, \
                          **/proxy.ts, \
                          **/apps/tools-index/data/**, \
                          **/netlify/**/*, \
                          **/scripts/**, \
                          **/__mocks__/**/*, \
                          **/apps/salary-calculator/data/**, \
                          **/apps/travel-insurance-directory/data/**, \
                          **/apps/evidence-hub/data/**, \
                          **/apps/fuel-finder/data/**, \
                          **/apps/pension-calculator/data/**, \
                          **/apps/e2e/**

sonar.coverage.inclusions=**/pages/api/**, \

sonar.cpd.exclusions=**/pages/[language]/**, \
                     **/pages/[lang]/**, \
                     **/pages/_document.tsx, \
                     **/pages/_app.tsx, \
                     **/netlify/**, \
                     **/apps/**/mocks/*, \
                     **/libs/**/__mocks__/*, \
                     **/libs/**/data/*, \
                     **/mockData.tsx, \
                     **/apps/**/next.config.js, \
                     **/*.config.*, \
                     **/apps/pensions-dashboard/components/Header/*, \
                     **/apps/tools-index/components/Tool/**, \
                     **/apps/tools-index/pages/api/test-embed.ts, \
                     **/apps/tools-index/pages/api/test-embed.test.ts, \
                     **/libs/shared/mps/src/components/Footer/*, \
                     **/libs/shared/mps/src/components/Header/*, \
                     **/libs/shared/mps/src/components/Navigation/*, \
                     **/libs/shared/mps/src/components/SearchForm/*, \
                     **/libs/shared/mps/src/utils/search/*, \
                     **/apps/e2e/**, \
                     **/apps/**/proxy.ts, \
                     **/libs/shared/pension-tools/src/utils/filterQuery/**, \
                     **/apps/baby-money-timeline/**, \
                     **/apps/savings-calculator/**, \
                     **/apps/moneyhelper-booking-forms/lib/utils/submitFlow.ts, \
                     **/apps/salary-calculator/utils/rates/constants.ts, \

# Ignore the below issues
sonar.issue.ignore.multicriteria=e1, e2, e3, e4
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6479
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S6551
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S3358
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*
sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S6819
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*
sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S7764
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*
# Code coverage
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
