parameters:
  - name: platform
    type: string
  - name: displayName
    type: string
  - name: dependsOn
    type: string
    default: ""
  - name: condition
    type: string
    default: succeededOrFailed()

jobs:
  - job: ${{ parameters.platform }}_Tests
    timeoutInMinutes: 0
    displayName: ${{ parameters.displayName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}

    steps:
      - task: UseNode@1
        inputs:
          version: "22.23.2"
        displayName: "Install Node.js"

      - script: |
          node -v
          npm -v
          npx -v
        displayName: "Verify Node.js / npm / npx"

      - script: npm install --no-audit
        displayName: "Install Dependencies"

      - script: |
          npx playwright@1.56.1 install --with-deps
        displayName: "Install Playwright browsers (1.56.1)"

      - script: >
          npx nx run pensions-dashboard-e2e:e2e-lambdatest:${{ parameters.platform }}
          --config=apps/e2e/pensions-dashboard-e2e/playwright.lambdatest.config.ts
          --output=results/${{ parameters.platform }}/test-results
          --skip-nx-cache
        # -- --grep "How these values are calculated accordion displays BS message"
        # Explicitly name test file --testFiles=apps/e2e/pensions-dashboard-e2e/src/e2e/tests/logout.spec.ts

        displayName: "Run ${{ parameters.displayName }} tests"
        env:
          E2E_TARGET: $(E2E_TARGET)
          BASE_URL: $(PENSION_DASHBOARD_URL)
          MHPD_API_URL: $(MHPD_API_DOMAIN)
          NETLIFY_PASSWORD: $(netlify-password)
          MHPD_COMPOSER_API_URL: $(MHPD_COMPOSER_API_URL)
          LT_USERNAME: $(LT_USERNAME)
          LT_ACCESS_KEY: $(lt-access-key)
          PLAYWRIGHT_HTML_REPORT: results/${{ parameters.platform }}/playwright-report
          PW_TEST_HTML_REPORT_OPEN: "never"
          CI: "true"

      - task: PublishBuildArtifacts@1
        condition: succeededOrFailed()
        inputs:
          pathToPublish: results/${{ parameters.platform }}/playwright-report
          artifactName: ${{ parameters.platform }}-playwright-report
          publishLocation: "Container"
