export enum PensionOptionPage {
  RETIRE_LATER = 1,
  GUARANTEED_INCOME,
  FLEXIBLE_INCOME,
  LUMP_SUMS,
  POT_IN_ONE_GO,
  MIX_OPTIONS,
}

export enum Question {
  KEEPING_TRACK_OF_PENSIONS = 9,
  TRANSFERRING_PENSION = 10,
  RETIREMENT_BUDGET = 11,
  STATE_PENSION = 12,
  STATE_BENEFITS = 13,
  PAY_DEBTS = 14,
  LIVE_OVERSEAS = 15,
  MADE_A_WILL = 17,
  POWER_OF_ATTORNEY = 18,
}

export enum Detail {
  PENSION_BASICS = 2101,
  PROTECTING_YOUR_PENSION = 2102,
  INCOME_AND_SAVINGS = 2201,
  DEBTS_AND_REPAYMENTS = 2301,
  YOUR_HOME = 2401,
  HEALTH_AND_FAMILY = 2501,
}

export const DATABASE_NAME = process.env.PWD_DB_NAME ?? '';
export const DATABASE_ID = process.env.PWD_DB_ID ?? '';
