[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/pension-calculator package.json libs/shared"
  command = "npx nx run pension-calculator:build"

[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    targetPort = 4311
    autoLaunch = false
    base = "/"
    command = "npx nx run pension-calculator:serve"

[[redirects]]
    from = "/fn/api/:operation"
    to = "/.netlify/functions/redis?operation=:operation"
    status = 200

[[plugins]]
    package = "@netlify/plugin-csp-nonce"
    [plugins.inputs]
        reportOnly = false
