name: Fix package build error for Netlify sites

trigger: none

variables:
  - group: 'Maps-Apps-Pipeline-Secrets'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      pip install requests
    displayName: 'Install requests package'

  - script: |
      python netlify/scripts/build-error-fix.py
    displayName: 'Re-build with cleared cache for each site'
    env:
      NETLIFY_TOKEN: $(netlify-token)

  - script: |
      echo "Waiting for builds to complete..."
      sleep 2700
    displayName: 'Waiting for builds to complete'

  - script: |
      python netlify/scripts/update-environment-variable.py
    displayName: 'Reset FORCE_BUILD env variable for each site'
    env:
      NETLIFY_TOKEN: $(netlify-token)
      VARIABLE_NAME: 'FORCE_BUILD'
      VARIABLE_VALUE: 'false'
      ALL_SITES: 'true'
