export const mockAccount = {
  id: '1',
  name: 'Account 1',
  providerName: 'Provider 1',
  access: ['Online', 'In-branch'],
  arrangedODDetailBrochure: 'OD brochure 1',
  arrangedODExample1: { amount: 1000, currency: 'GBP', scale: 2 },
  arrangedODExample2: { amount: 2000, currency: 'USD', scale: 2 },
  atmEU50Cost: { amount: 1.5, currency: 'EUR', scale: 2 },
  atmMaxFreeWithdrawalUK: 200,
  atmWithdrawalCharge: { amount: 1.0, currency: 'GBP', scale: 2 },
  atmWithdrawalChargePercent: 2.5,
  atmWorld50Cost: { amount: 2.0, currency: 'USD', scale: 2 },
  bacsCharge: { amount: 0.5, currency: 'GBP', scale: 2 },
  chapsCharge: { amount: 5.0, currency: 'GBP', scale: 2 },
  debitCardIssueFee: { amount: 10.0, currency: 'GBP', scale: 2 },
  debitCardReplacementFee: { amount: 15.0, currency: 'GBP', scale: 2 },
  debitCardReplacementFeeBrochure: 'Replacement brochure',
  debitEU50Cost: { amount: 1.0, currency: 'EUR', scale: 2 },
  debitWorld50Cost: { amount: 2.5, currency: 'USD', scale: 2 },
  directDebitCharge: { amount: 1.0, currency: 'GBP', scale: 2 },
  fasterPaymentsCharge: { amount: 0.25, currency: 'GBP', scale: 2 },
  features: ['Online banking', 'Mobile app'],
  intCashWithdrawDetail: 'Cash withdrawal info',
  intDebitCardPayDetail: 'Debit card pay info',
  intPaymentsInDetail: 'Payments in info',
  intPaymentsOutDetail: 'Payments out info',
  minimumMonthlyCredit: { amount: 500, currency: 'GBP', scale: 2 },
  minimumMonthlyCreditBrochure: 'Minimum credit brochure',
  monthlyChargeBrochure: 'Monthly charge brochure',
  monthlyFee: { amount: 10.0, currency: 'GBP', scale: 2 },
  otherChargesBrochure: 'Other charges brochure',
  overdraftFacility: true,
  paidItemDetail: 'Paid item info',
  payInEUMaxChrg: { amount: 0.5, currency: 'EUR', scale: 2 },
  payInEUMinChrg: { amount: 0.1, currency: 'EUR', scale: 2 },
  payInWorldMaxChrg: { amount: 1.0, currency: 'USD', scale: 2 },
  payInWorldMinChrg: { amount: 0.5, currency: 'USD', scale: 2 },
  payOutEUMaxChrg: { amount: 1.0, currency: 'EUR', scale: 2 },
  payOutEUMinChrg: { amount: 0.2, currency: 'EUR', scale: 2 },
  payOutWorldMaxChrg: { amount: 2.0, currency: 'USD', scale: 2 },
  payOutWorldMinChrg: { amount: 1.0, currency: 'USD', scale: 2 },
  representativeAPR: 19.9,
  standingOrderCharge: { amount: 1.0, currency: 'GBP', scale: 2 },
  stoppedChequeCharge: { amount: 10.0, currency: 'GBP', scale: 2 },
  transactionFee: { amount: 0.1, currency: 'GBP', scale: 2 },
  transactionFeeBrochure: 'Transaction fee brochure',
  type: 'Current Account',
  ukCashWithdrawalDetail: 'UK cash withdrawal info',
  unarrangedODDetailBrochure: 'Unarranged OD brochure',
  unauthODMonthlyCap: { amount: 500, currency: 'GBP', scale: 2 },
  unauthorisedOverdraftEar: 29.9,
  unpaidItemDetail: 'Unpaid item info',
  url: 'https://example.com',
};

export const mockAccounts = [
  { ...mockAccount, id: '1', name: 'Account 1', providerName: 'Provider 1' },
  { ...mockAccount, id: '2', name: 'Account 2', providerName: 'Provider 2' },
];
